ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/backend-protocol: HTTP
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/affinity: "cookie"
    nginx.ingress.kubernetes.io/session-cookie-max-age: "172800"
  
  tls: 
    - secretName: dftfrontend-secret
      hosts:
        - dft.dev.demo.catena-x.net
        
  resources:
  limits:
    cpu: 400m
    memory: 600Mi
  requests:
    cpu: 400m
    memory: 600Mi
